In [2]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2=np.array([[1,2,3],[4,5,6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3-dim",arr3,sep='\n',end='\n\n')

1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

3-dim
[[1 2 3]
 [4 5 6]
 [7 8 9]]



In [3]:
zeros=np.zeros((10,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones=np.ones((11,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
identity=np.eye(7)
print(identity)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [7]:
full_array=np.full((10,3),True)
print(full_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
full_array=np.full((10,3),[1,2,3])
print(full_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [14]:
full_array=np.full((10,5),False)
print(full_array)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [15]:
range_arr=np.arange(2,21,2)
print(range_arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [21]:
line_space=np.linspace(0,50,11)
print(line_space)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [22]:
rand_int=np.random.randint(10,60)
print(rand_int)

40


In [23]:
rand_int=np.random.randint(1,6,(5,5))
print(rand_int)

[[5 3 1 2 5]
 [5 4 4 2 2]
 [3 5 3 2 5]
 [4 2 2 2 4]
 [1 2 5 4 3]]


In [27]:
random_choice=np.random.choice(['html','css','javascript','python','mysql'],2)
print(random_choice)

['mysql' 'javascript']


In [28]:
np.random.seed(10)

rand_arr=np.random.randint(6)
print(rand_arr)

1


In [30]:
arr=np.array([[1,2],[4,5],[6,7],[7,8],[8,9]])
print(arr.shape)

(5, 2)


In [32]:
reshaped=arr.reshape(1,10)
print(reshaped)

[[1 2 4 5 6 7 7 8 8 9]]


In [33]:
a=np.array(([1,2,3,4],[1,2,3,4]))
flattened=a.flatten()
print(flattened)

[1 2 3 4 1 2 3 4]


In [34]:
transposed=arr.T
print(transposed)

[[1 4 6 7 8]
 [2 5 7 8 9]]


In [35]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[1:4:2])
print(arr[:3])
print(arr[:2])

10
50
[20 30 40]
[20 40]
[10 20 30]
[10 20]


In [38]:
import numpy as np

matrix=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(matrix[0,2])
print(matrix[0,1])
print(matrix[2,0])
print(matrix[0:3,0])
print(matrix[0:3,0:2])

30
20
70
[10 40 70]
[[10 20]
 [40 50]
 [70 80]]


In [39]:
arr=np.array([4,9,16,25,36])

In [40]:
print(arr+1)
print(arr*2)
print(arr**2)
print(np.sqrt(arr))

[ 5 10 17 26 37]
[ 8 18 32 50 72]
[  16   81  256  625 1296]
[2. 3. 4. 5. 6.]


In [41]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [42]:
print(np.var(arr))
print(np.std(a))

130.8
1.118033988749895
